import type { User, Area, Task, AreaId, Role } from './types';

export const areas: Area[] = [
  { id: 'servicio', nombre: 'Servicio', color: '#FF6B6B', responsable: 'user-admin-1', descripcion: 'Atención al cliente y servicio de mesas.', activa: true },
  { id: 'cocina', nombre: 'Cocina', color: '#4ECDC4', responsable: 'user-admin-1', descripcion: 'Preparación de alimentos.', activa: true },
  { id: 'limpieza', nombre: 'Limpieza', color: '#45B7D1', responsable: 'user-admin-2', descripcion: 'Mantenimiento y limpieza de instalaciones.', activa: true },
  { id: 'almacen', nombre: 'Almacén', color: '#96CEB4', responsable: 'user-admin-2', descripcion: 'Gestión de inventario y suministros.', activa: true },
  { id: 'equipos', nombre: 'Equipos', color: '#FFEAA7', responsable: 'user-admin-1', descripcion: 'Mantenimiento de equipos de cocina.', activa: true },
  { id: 'administracion', nombre: 'Administración', color: '#DDA0DD', responsable: 'user-superadmin-1', descripcion: 'Gestión general y administrativa.', activa: true },
];

export const users: User[] = [
  {
    userId: 'user-superadmin-1',
    email: 'arvecladu@gmail.com',
    nombre: 'Super Admin',
    rol: 'superadmin',
    area: 'administracion',
    activo: true,
    fechaCreacion: new Date('2023-01-01T12:00:00Z'),
    creadoPor: 'system',
    ultimoAcceso: new Date('2024-05-30T10:00:00Z'),
    avatarUrl: 'https://i.pravatar.cc/150?u=superadmin'
  },
  {
    userId: 'user-admin-1',
    email: 'admin1@comedor.com',
    nombre: 'Ana Gómez',
    rol: 'admin',
    area: 'cocina',
    activo: true,
    fechaCreacion: new Date('2023-02-15T12:00:00Z'),
    creadoPor: 'user-superadmin-1',
    ultimoAcceso: new Date('2024-05-30T11:00:00Z'),
    avatarUrl: 'https://i.pravatar.cc/150?u=admin1'
  },
  {
    userId: 'user-admin-2',
    email: 'admin2@comedor.com',
    nombre: 'Luis Pérez',
    rol: 'admin',
    area: 'limpieza',
    activo: true,
    fechaCreacion: new Date('2023-03-20T12:00:00Z'),
    creadoPor: 'user-superadmin-1',
    ultimoAcceso: new Date('2024-05-29T09:00:00Z'),
    avatarUrl: 'https://i.pravatar.cc/150?u=admin2'
  },
  {
    userId: 'user-comun-1',
    email: 'carlos@comedor.com',
    nombre: 'Carlos Ruiz',
    rol: 'comun',
    area: 'cocina',
    activo: true,
    fechaCreacion: new Date('2023-04-10T12:00:00Z'),
    creadoPor: 'user-admin-1',
    ultimoAcceso: new Date('2024-05-30T08:30:00Z'),
    avatarUrl: 'https://i.pravatar.cc/150?u=carlos'
  },
  {
    userId: 'user-comun-2',
    email: 'maria@comedor.com',
    nombre: 'María Fernández',
    rol: 'comun',
    area: 'servicio',
    activo: true,
    fechaCreacion: new Date('2023-04-11T12:00:00Z'),
    creadoPor: 'user-admin-1',
    ultimoAcceso: new Date('2024-05-30T14:00:00Z'),
    avatarUrl: 'https://i.pravatar.cc/150?u=maria'
  },
  {
    userId: 'user-comun-3',
    email: 'jose@comedor.com',
    nombre: 'José Martínez',
    rol: 'comun',
    area: 'limpieza',
    activo: true,
    fechaCreacion: new Date('2023-05-01T12:00:00Z'),
    creadoPor: 'user-admin-2',
    ultimoAcceso: new Date('2024-05-28T16:00:00Z'),
    avatarUrl: 'https://i.pravatar.cc/150?u=jose'
  },
];

export const tasks: Task[] = [
  {
    taskId: 'task-1',
    titulo: 'Limpieza profunda de la cocina',
    descripcion: 'Realizar una limpieza exhaustiva de todas las superficies, equipos y suelos de la cocina principal.',
    area: 'cocina',
    asignadoA: 'user-comun-1',
    creadoPor: 'user-admin-1',
    estado: 'en-progreso',
    prioridad: 'alta',
    periodicidad: 'semanal',
    fechaCreacion: new Date('2024-05-28T10:00:00Z'),
    fechaVencimiento: new Date('2024-06-05T23:59:00Z'),
    tiempoEstimado: 240,
    checklist: [
      { item: 'Limpiar hornos', completado: true },
      { item: 'Desinfectar mesas de trabajo', completado: true },
      { item: 'Barrer y fregar suelos', completado: false },
    ],
    evidencias: [],
    comentarios: [],
    tags: ['limpieza', 'cocina'],
    recurrente: true,
  },
  {
    taskId: 'task-2',
    titulo: 'Inventario de almacén seco',
    descripcion: 'Contar y registrar todas las existencias en el almacén de productos secos.',
    area: 'almacen',
    asignadoA: 'user-comun-3',
    creadoPor: 'user-admin-2',
    estado: 'pendiente',
    prioridad: 'media',
    periodicidad: 'mensual',
    fechaCreacion: new Date('2024-05-29T11:00:00Z'),
    fechaVencimiento: new Date('2024-06-10T23:59:00Z'),
    tiempoEstimado: 120,
    checklist: [],
    evidencias: [],
    comentarios: [],
    tags: ['inventario'],
    recurrente: true,
  },
  {
    taskId: 'task-3',
    titulo: 'Servir almuerzo',
    descripcion: 'Atender a los comensales durante el servicio de almuerzo.',
    area: 'servicio',
    asignadoA: 'user-comun-2',
    creadoPor: 'user-admin-1',
    estado: 'completada',
    prioridad: 'urgente',
    periodicidad: 'diaria',
    fechaCreacion: new Date('2024-05-29T12:00:00Z'),
    fechaVencimiento: new Date('2024-05-29T15:00:00Z'),
    fechaCompletado: new Date('2024-05-29T14:30:00Z'),
    tiempoEstimado: 180,
    checklist: [],
    evidencias: [],
    comentarios: [],
    tags: ['servicio'],
    recurrente: true,
  },
    {
    taskId: 'task-4',
    titulo: 'Revisión de extintores',
    descripcion: 'Verificar la fecha de caducidad y la presión de todos los extintores del comedor.',
    area: 'equipos',
    asignadoA: 'user-admin-2',
    creadoPor: 'user-superadmin-1',
    estado: 'pendiente',
    prioridad: 'alta',
    periodicidad: 'quincenal',
    fechaCreacion: new Date('2024-05-25T09:00:00Z'),
    fechaVencimiento: new Date('2024-06-02T17:00:00Z'),
    tiempoEstimado: 60,
    checklist: [],
    evidencias: [],
    comentarios: [],
    tags: ['seguridad', 'mantenimiento'],
    recurrente: true,
  },
  {
    taskId: 'task-5',
    titulo: 'Preparar Mise en Place para cena',
    descripcion: 'Cortar vegetales, preparar salsas y aderezos para el servicio de la cena.',
    area: 'cocina',
    asignadoA: 'user-comun-1',
    creadoPor: 'user-admin-1',
    estado: 'pendiente',
    prioridad: 'urgente',
    periodicidad: 'diaria',
    fechaCreacion: new Date('2024-05-30T16:00:00Z'),
    fechaVencimiento: new Date('2024-05-30T18:00:00Z'),
    tiempoEstimado: 90,
    checklist: [],
    evidencias: [],
    comentarios: [],
    tags: ['cocina', 'preparacion'],
    recurrente: true,
  },
];

export const stats = {
  total: 25,
  completadas: 18,
  pendientes: 7,
  eficiencia: (18 / 25) * 100,
  chartData: [
    { name: 'Carlos R.', eficiencia: 90 },
    { name: 'María F.', eficiencia: 75 },
    { name: 'José M.', eficiencia: 85 },
    { name: 'Ana G.', eficiencia: 95 },
  ],
  pieData: [
    { name: 'Cocina', value: 8, fill: 'hsl(var(--chart-1))' },
    { name: 'Servicio', value: 6, fill: 'hsl(var(--chart-2))' },
    { name: 'Limpieza', value: 5, fill: 'hsl(var(--chart-3))' },
    { name: 'Almacén', value: 4, fill: 'hsl(var(--chart-4))' },
    { name: 'Equipos', value: 2, fill: 'hsl(var(--chart-5))' },
  ],
};
