
'use client';

import React, { useState, useMemo, useEffect } from 'react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { useCollection, useFirestore, useMemoFirebase, useUser } from '@/firebase';
import { collection, query, where, orderBy, doc } from 'firebase/firestore';
import { addDocumentNonBlocking } from '@/firebase/non-blocking-updates';
import type { User, EvaluationCriterion } from '@/lib/types';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';
import { EvaluationForm } from '@/components/evaluations/evaluation-form';
import { useToast } from '@/components/ui/toast';
import { Star, Loader2, ArrowLeft } from 'lucide-react';
import Link from 'next/link';

function generateMonthOptions() {
  const options = [];
  const now = new Date();
  for (let i = 0; i < 12; i++) {
    const date = new Date(now.getFullYear(), now.getMonth() - i, 1);
    options.push({
      value: format(date, 'yyyy-MM'),
      label: format(date, 'MMMM yyyy', { locale: es }),
    });
  }
  return options;
}

export default function MonthlyEvaluationPage() {
  const firestore = useFirestore();
  const { user: authUser, isUserLoading } = useUser();
  const { toast } = useToast();

  const [selectedUser, setSelectedUser] = useState<string | null>(null);
  const [selectedPeriod, setSelectedPeriod] = useState<string>(format(new Date(), 'yyyy-MM'));
  const [isSubmitting, setIsSubmitting] = useState(false);

  const usersQuery = useMemoFirebase(() => {
    if (!firestore || !authUser) return null;
    return query(collection(firestore, 'users'), orderBy('name'));
  }, [firestore, authUser]);

  const criteriaQuery = useMemoFirebase(() => {
    if (!firestore || !authUser) return null;
    return query(
      collection(firestore, 'evaluationCriteria'),
      where('isActive', '==', true),
      orderBy('name')
    );
  }, [firestore, authUser]);

  const { data: users, isLoading: isLoadingUsers } = useCollection<User>(usersQuery);
  const { data: criteria, isLoading: isLoadingCriteria } = useCollection<EvaluationCriterion>(criteriaQuery);

  const monthOptions = useMemo(() => generateMonthOptions(), []);

  const handleSaveEvaluation = async (scores: Record<string, { score: number; comment: string }>, totalScore: number) => {
    if (!firestore || !selectedUser || !authUser) return;
    setIsSubmitting(true);

    const evaluationData = {
      userId: selectedUser,
      period: selectedPeriod,
      scores: Object.entries(scores).map(([criterionId, data]) => ({
        criterionId,
        score: data.score,
        comment: data.comment,
      })),
      totalScore,
      evaluatorId: authUser.uid,
      evaluationDate: new Date(),
    };

    try {
        const evaluationRef = collection(firestore, 'monthlyEvaluations');
        // The ID will be auto-generated by Firestore
        await addDocumentNonBlocking(evaluationRef, evaluationData);

        toast({
            title: "Evaluación Guardada",
            description: `La evaluación para el período ${selectedPeriod} ha sido registrada.`,
        });
        setSelectedUser(null); // Reset selection
    } catch (error) {
        console.error("Error al guardar la evaluación:", error);
        toast({
            variant: 'destructive',
            title: "Error al Guardar",
            description: "No se pudo registrar la evaluación.",
        });
    } finally {
        setIsSubmitting(false);
    }
  };
  
  const isLoading = isLoadingUsers || isLoadingCriteria || isUserLoading;
  const canEvaluate = selectedUser && criteria && criteria.length > 0;

  return (
    <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-8">
      <div className="flex items-center gap-4">
          <Button variant="outline" size="icon" className="h-7 w-7" asChild>
            <Link href="/attendance">
              <ArrowLeft className="h-4 w-4" />
              <span className="sr-only">Volver a RRHH</span>
            </Link>
          </Button>
          <h1 className="text-xl font-semibold md:text-2xl">
            Evaluación de Desempeño Mensual
          </h1>
        </div>

      <Card>
        <CardHeader>
          <CardTitle>Seleccionar Empleado y Período</CardTitle>
          <CardDescription>
            Elige el empleado y el mes que deseas evaluar.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex items-center gap-2 text-muted-foreground">
                <Loader2 className="h-5 w-5 animate-spin" />
                <span>Cargando datos...</span>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">Empleado a Evaluar</label>
                <Select onValueChange={setSelectedUser} value={selectedUser || undefined}>
                  <SelectTrigger>
                    <SelectValue placeholder="Selecciona un empleado..." />
                  </SelectTrigger>
                  <SelectContent>
                    {users?.map((user) => (
                      <SelectItem key={user.id} value={user.id}>
                        {user.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">Período</label>
                <Select onValueChange={setSelectedPeriod} value={selectedPeriod}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {monthOptions.map((option) => (
                      <SelectItem key={option.value} value={option.value}>
                        {option.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
      
      {canEvaluate ? (
        <EvaluationForm 
            key={`${selectedUser}-${selectedPeriod}`} // Re-mount form on user/period change
            criteria={criteria!}
            onSave={handleSaveEvaluation}
            isSubmitting={isSubmitting}
        />
      ) : (
        <Card className="mt-8 border-dashed">
            <CardHeader className="text-center">
                <Star className="mx-auto h-12 w-12 text-muted-foreground/50" />
                <CardTitle className="mt-4">Listo para Evaluar</CardTitle>
                <CardDescription>
                   {isLoadingCriteria ? "Cargando criterios..." :
                    !criteria || criteria.length === 0 ? "No hay criterios de evaluación activos. Configúralos en la Matriz de Evaluación." :
                    "Selecciona un empleado para comenzar la evaluación de su desempeño."
                   }
                </CardDescription>
            </CardHeader>
        </Card>
      )}

    </main>
  );
}
